import React from 'react';
import { PlaygroundCard } from "@/components/system/PlaygroundCard";
import { useFilterStore } from "@/store/useFilterStore";
import { HeroGradient } from "@/components/motionary/blocks/HeroGradient";
import { BentoGrid } from "@/components/motionary/blocks/BentoGrid";
import { PricingSection } from "@/components/motionary/blocks/PricingSection";
import { LandingPage } from "@/components/motionary/blocks/LandingPage";
import { ParticleCanvas } from "@/components/motionary/advanced/ParticleCanvas";
import { MagneticButton } from "@/components/motionary/atomic/MagneticButton";
import { LiquidButton } from "@/components/motionary/atomic/LiquidButton";
import { JellyButton } from "@/components/motionary/atomic/JellyButton";
import { KineticText } from "@/components/motionary/atomic/KineticText";
import { FloatingInput } from "@/components/motionary/atomic/FloatingInput";
import { ShakeInput } from "@/components/motionary/atomic/ShakeInput";
import { SwipeToDelete } from "@/components/motionary/mobile/SwipeToDelete";
import * as Buttons from "@/components/motionary/atomic/ButtonVariants";
import * as Text from "@/components/motionary/atomic/TextVariants";
import * as Cards from "@/components/motionary/atomic/CardVariants";
import * as Nav from "@/components/motionary/atomic/NavVariants";
import * as InputVars from "@/components/motionary/atomic/InputVariants";
import * as Loaders from "@/components/motionary/atomic/LoaderVariants";
import * as Images from "@/components/motionary/atomic/ImageVariants";
import * as Micro from "@/components/motionary/atomic/MicroVariants";
import * as Backgrounds from "@/components/motionary/atomic/BackgroundVariants";
import * as Data from "@/components/motionary/atomic/DataVariants";
import * as Feedback from "@/components/motionary/atomic/FeedbackVariants";
import * as Social from "@/components/motionary/atomic/SocialVariants";
import * as Ecom from "@/components/motionary/atomic/EcommerceVariants";
import * as Game from "@/components/motionary/atomic/GameVariants";
import * as Transitions from "@/components/motionary/atomic/TransitionVariants";
import * as Media from "@/components/motionary/atomic/MediaVariants";
import * as Device from "@/components/motionary/atomic/DeviceVariants";
import { useBubbleSound } from "@/hooks/useBubbleSound";
import { Footer } from "@/components/system/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Feedback Components for AI & Vibe Coding | Motionary",
  description: "User Feedback components optimized for AI development. Toasts, notifications, alerts, and loading states with engaging animations.",
  keywords: ["react feedback","ui notifications","ai coding","vibe coding","toast messages","loading states","alert components","user feedback"],
};

const BLOCK_STYLE = ["gradient", "glassmorphism"];
const MICRO_STYLE = ["minimal", "cyber"];

export default function FeedbackPage() {
  return (
    <div className="min-h-screen pt-24 pb-20">
      <div className="max-w-[1920px] mx-auto px-6 md:px-12 space-y-8">
        
        <div className="mb-12 flex items-end gap-6 sticky top-0 bg-background/80 backdrop-blur-xl py-4 z-40 border-b border-white/5">
           <h2 className="text-4xl font-bold tracking-tight text-white"><span className="text-secondary mr-4 font-mono text-2xl">07.</span>Feedback</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Error Toast: click motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Error Toast" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.ErrorToast /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Warning: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Warning" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.WarningAlert /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Info Banner: load motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Info Banner" trigger="Load" codePath="atomic/FeedbackVariants"><Feedback.InfoBanner /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Bell Shake: hover motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Bell Shake" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.BellShake /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Confetti: click motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Confetti" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.ConfettiBurst /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Typing...: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Typing..." trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.TypingIndicator /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Signal: static motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Signal" trigger="Static" codePath="atomic/FeedbackVariants"><Feedback.SignalStrength /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="404 Glitch: hover motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="404 Glitch" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.Error404 /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Empty State: static motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Empty State" trigger="Static" codePath="atomic/FeedbackVariants"><Feedback.EmptyBox /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Pulse Beacon: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Pulse Beacon" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.PulseBeacon /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Access Denied: click motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Access Denied" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.LockShake /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Timer: static motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Timer" trigger="Static" codePath="atomic/FeedbackVariants"><Feedback.UrgencyTimer /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Online: static motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Online" trigger="Static" codePath="atomic/FeedbackVariants"><Feedback.OnlineBadge /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Offline: static motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Offline" trigger="Static" codePath="atomic/FeedbackVariants"><Feedback.OfflineOverlay /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Skeleton Card: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Skeleton Card" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.SkeletonCard /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Upload Check: load motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Upload Check" trigger="Load" codePath="atomic/FeedbackVariants"><Feedback.UploadComplete /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Battery Low: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Battery Low" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.BatteryLow /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Fingerprint: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Fingerprint" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.FingerprintScan /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Eye Tracking: mouse motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Eye Tracking" trigger="Mouse" codePath="atomic/FeedbackVariants"><Feedback.EyeTracking /></PlaygroundCard>
                    <PlaygroundCard styleTags={['modern','stack']} compType="element" promptDescription="Stacked Toast: hover motion treatment with card stack notification reveal. Built with Tailwind CSS." title="Stacked Toast" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.StackedToast /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Progress Toast: hover motion treatment with progress bar completion. Built with Tailwind CSS." title="Progress Toast" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.ProgressToast /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern']} compType="element" promptDescription="Slide In Notify: hover motion treatment with notification drawer from edge. Built with Tailwind CSS." title="Slide In Notify" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.SlideInNotify /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal','loading']} compType="element" promptDescription="Skeleton Shimmer: loop motion treatment with loading placeholder animation. Built with Tailwind CSS." title="Skeleton Shimmer" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.SkeletonShimmer /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal','loading']} compType="element" promptDescription="Orbit Spinner: loop motion treatment with dual counter-rotating rings. Built with Tailwind CSS." title="Orbit Spinner" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.OrbitSpinner /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal','audio']} compType="element" promptDescription="Dot Wave: loop motion treatment with vertical bar wave. Built with Tailwind CSS." title="Dot Pulse Wave" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.DotPulseWave /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern','gradient']} compType="element" promptDescription="Liquid Progress: loop motion treatment with oscillating gradient bar. Built with Tailwind CSS." title="Liquid Progress" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.LiquidProgress /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction','minimal']} compType="element" promptDescription="Success Check: hover motion treatment with SVG path drawing. Built with Tailwind CSS." title="Success Check" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.SuccessCheck /></PlaygroundCard>
            <PlaygroundCard styleTags={['feedback','interaction']} compType="element" promptDescription="Error Shake: hover motion treatment with warning box vibration. Built with Tailwind CSS." title="Error Shake Box" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.ErrorShakeBox /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Wifi Search: hover motion treatment with signal wave ping. Built with Tailwind CSS." title="Wifi Searching" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.WifiSearching /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Battery Charge: hover motion treatment with fill animation and color shift. Built with Tailwind CSS." title="Battery Charge" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.BatteryCharge /></PlaygroundCard>
            <PlaygroundCard styleTags={['fun','minimal']} compType="element" promptDescription="Floating Ghost: loop motion treatment with bounce animation for empty state. Built with Tailwind CSS." title="Floating Ghost" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.FloatingGhost /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Search Magnifier: hover motion treatment with icon scale and dot badge. Built with Tailwind CSS." title="Search Magnifier" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.SearchMagnifier /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction','warning']} compType="element" promptDescription="Delete Confirm: hover motion treatment with text swap and background fill. Built with Tailwind CSS." title="Delete Confirm" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.DeleteConfirm /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Copy Success: focus/click motion treatment with state toggle feedback. Built with Tailwind CSS." title="Copy Success" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.CopySuccess /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction','modern']} compType="element" promptDescription="Download Expand: hover motion treatment with circular button expansion. Built with Tailwind CSS." title="Download Btn" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.DownloadBtn /></PlaygroundCard>
            <PlaygroundCard styleTags={['social']} compType="element" promptDescription="Like Reaction: click motion treatment with heart color and floating count. Built with Tailwind CSS." title="Like Reaction" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.LikeReaction /></PlaygroundCard>
            <PlaygroundCard styleTags={['social','minimal']} compType="element" promptDescription="Typing Dots: loop motion treatment with chat bubble bounce. Built with Tailwind CSS." title="Typing Dots" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.TypingDots /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Badge Pulse: loop motion treatment with ping animation on badge. Built with Tailwind CSS." title="Badge Pulse" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.BadgePulse /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Cloud Upload: hover motion treatment with bouncing cloud icon. Built with Tailwind CSS." title="Cloud Upload" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.CloudUpload /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Save Spinner: hover motion treatment with rotating sync icon. Built with Tailwind CSS." title="Save Spinner" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.SaveSpinner /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Lock Access: hover motion treatment with lock shackle movement. Built with Tailwind CSS." title="Lock Access" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.LockAccess /></PlaygroundCard>
            <PlaygroundCard styleTags={['media']} compType="element" promptDescription="Play Pause: hover motion treatment with shape morph scale. Built with Tailwind CSS." title="Play Pause" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.PlayPause /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Hover Tooltip: hover motion treatment with fade-in slide-up tooltip. Built with Tailwind CSS." title="Hover Tooltip" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.HoverTooltip /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Pulse Ring: loop motion treatment with radar ping effect. Built with Tailwind CSS." title="Pulse Ring" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.PulseRing /></PlaygroundCard>
            <PlaygroundCard styleTags={['loading']} compType="element" promptDescription="Step Progress: loop motion treatment with multi-step loader. Built with Tailwind CSS." title="Step Progress" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.StepProgress /></PlaygroundCard>
            <PlaygroundCard styleTags={['cyber']} compType="element" promptDescription="Glitch Warning: hover motion treatment with warning scan. Built with Tailwind CSS." title="Glitch Warning" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.GlitchWarning /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="File Uploading: loop motion treatment with file icon bounce and bar shimmer. Built with Tailwind CSS." title="File Uploading" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.FileUploading /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Card Select: hover motion treatment with radio selection simulation. Built with Tailwind CSS." title="Card Select" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.CardSelect /></PlaygroundCard>
            <PlaygroundCard styleTags={['cyber','neon']} compType="element" promptDescription="Status Orb: loop motion treatment with glowing orb pulse. Built with Tailwind CSS." title="Status Orb" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.StatusOrb /></PlaygroundCard>
            <PlaygroundCard styleTags={['alert']} compType="element" promptDescription="Banner Slide: hover motion treatment with notification bar. Built with Tailwind CSS." title="Banner Slide Down" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.BannerSlideDown /></PlaygroundCard>
            <PlaygroundCard styleTags={['modal']} compType="element" promptDescription="Modal Pop: hover motion treatment with spring entrance. Built with Tailwind CSS." title="Modal Pop Center" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.ModalPopCenter /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Inline Message: focus motion treatment with error reveal. Built with Tailwind CSS." title="Inline Message Fade" trigger="Focus" codePath="atomic/FeedbackVariants"><Feedback.InlineMessageFade /></PlaygroundCard>
            <PlaygroundCard styleTags={['status']} compType="element" promptDescription="Badge Count: loop motion treatment with attention ping. Built with Tailwind CSS." title="Notification Badge Count" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.NotificationBadgeCount /></PlaygroundCard>
            <PlaygroundCard styleTags={['time']} compType="element" promptDescription="Circular Timer: loop motion treatment with countdown stroke. Built with Tailwind CSS." title="Circular Timer" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.CircularTimer /></PlaygroundCard>
            <PlaygroundCard styleTags={['loading']} compType="element" promptDescription="Skeleton List: loop motion treatment with content placeholder. Built with Tailwind CSS." title="Skeleton List Load" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.SkeletonListLoad /></PlaygroundCard>
            <PlaygroundCard styleTags={['creative']} compType="element" promptDescription="Liquid Loader: loop motion treatment with fluid rise. Built with Tailwind CSS." title="Liquid Loader Fill" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.LiquidLoaderFill /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Step Tracker: load motion treatment with sequence reveal. Built with Tailwind CSS." title="Step Tracker Vertical" trigger="Load" codePath="atomic/FeedbackVariants"><Feedback.StepTrackerVertical /></PlaygroundCard>
            <PlaygroundCard styleTags={['social']} compType="element" promptDescription="Online Dot: loop motion treatment with avatar status. Built with Tailwind CSS." title="Online Dot Pulse" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.OnlineDotPulse /></PlaygroundCard>
            <PlaygroundCard styleTags={['status']} compType="element" promptDescription="Sync Refresh: loop motion treatment with spin text. Built with Tailwind CSS." title="Sync Refresh Icon" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.SyncRefreshIcon /></PlaygroundCard>
            <PlaygroundCard styleTags={['tech']} compType="element" promptDescription="Cable Charge: loop motion treatment with power flow. Built with Tailwind CSS." title="Battery Charge Cable" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.BatteryChargeCable /></PlaygroundCard>
            <PlaygroundCard styleTags={['tech']} compType="element" promptDescription="Wifi Waves: loop motion treatment with radio emission. Built with Tailwind CSS." title="Wifi Signal Waves" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.WifiSignalWaves /></PlaygroundCard>
            <PlaygroundCard styleTags={['feedback']} compType="element" promptDescription="Haptic Shake: click motion treatment with vibration feel. Built with Tailwind CSS." title="Haptic Shake Btn" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.HapticShakeBtn /></PlaygroundCard>
            <PlaygroundCard styleTags={['material']} compType="element" promptDescription="Ripple Tap: click motion treatment with touch feedback. Built with Tailwind CSS." title="Ripple Tap Effect" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.RippleTapEffect /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Glow Success: click motion treatment with active state shine. Built with Tailwind CSS." title="Glow Success Card" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.GlowSuccessCard /></PlaygroundCard>
            <PlaygroundCard styleTags={['fun']} compType="element" promptDescription="Confetti Burst: click motion treatment with icon celebration. Built with Tailwind CSS." title="Confetti Burst Icon" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.ConfettiBurstIcon /></PlaygroundCard>
            <PlaygroundCard styleTags={['social']} compType="element" promptDescription="Typing Bubble: loop motion treatment with chat status. Built with Tailwind CSS." title="Typing Indicator Bubble" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.TypingIndicatorBubble /></PlaygroundCard>
            <PlaygroundCard styleTags={['system']} compType="element" promptDescription="Connection Status: loop motion treatment with state label. Built with Tailwind CSS." title="Connection Status" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.ConnectionStatus /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Empty Float: loop motion treatment with idle animation. Built with Tailwind CSS." title="Empty State Float" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.EmptyStateFloat /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Drag Active: hover motion treatment with drop acceptance. Built with Tailwind CSS." title="Drag Drop Zone Active" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.DragDropZoneActive /></PlaygroundCard>
            <PlaygroundCard styleTags={['system']} compType="element" promptDescription="System Update: loop motion treatment with progress shimmer. Built with Tailwind CSS." title="System Update Bar" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.SystemUpdateBar /></PlaygroundCard>
            <PlaygroundCard styleTags={['media']} compType="element" promptDescription="Mic Listen: loop motion treatment with recording waves. Built with Tailwind CSS." title="Microphone Listening" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.MicrophoneListening /></PlaygroundCard>
            <PlaygroundCard styleTags={['security']} compType="element" promptDescription="Face Frame: loop motion treatment with identity scan. Built with Tailwind CSS." title="Face Scan Frame" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.FaceScanFrame /></PlaygroundCard>
            <PlaygroundCard styleTags={['security']} compType="element" promptDescription="Password Dots: loop motion treatment with hidden character bounce. Built with Tailwind CSS." title="Password Hidden" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.PasswordHidden /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Scroll Indicator: loop motion treatment with mouse wheel hint. Built with Tailwind CSS." title="Scroll Indicator" trigger="Loop" codePath="atomic/FeedbackVariants"><Feedback.ScrollIndicator /></PlaygroundCard>
            <PlaygroundCard styleTags={['accessibility']} compType="element" promptDescription="Focus Ring: focus motion treatment with outline snap. Built with Tailwind CSS." title="Focus Ring Expand" trigger="Focus" codePath="atomic/FeedbackVariants"><Feedback.FocusRingExpand /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern']} compType="element" promptDescription="Spotlight Card: hover motion treatment with light reveal. Built with Tailwind CSS." title="Hover Spotlight Card" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.HoverSpotlightCard /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Click Underline: click motion treatment with text emphasis. Built with Tailwind CSS." title="Click Ripple Text" trigger="Click" codePath="atomic/FeedbackVariants"><Feedback.ClickRippleText /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Tooltip Delay: hover motion treatment with timed reveal. Built with Tailwind CSS." title="Tooltip Delay" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.TooltipDelay /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Menu Close: hover motion treatment with icon morph to minus. Built with Tailwind CSS." title="Menu Close Button" trigger="Hover" codePath="atomic/FeedbackVariants"><Feedback.MenuCloseButton /></PlaygroundCard>
</div>
      
      </div>
    </div>
  );
}
