import React from 'react';
import { PlaygroundCard } from "@/components/system/PlaygroundCard";
import { useFilterStore } from "@/store/useFilterStore";
import { HeroGradient } from "@/components/motionary/blocks/HeroGradient";
import { BentoGrid } from "@/components/motionary/blocks/BentoGrid";
import { PricingSection } from "@/components/motionary/blocks/PricingSection";
import { LandingPage } from "@/components/motionary/blocks/LandingPage";
import { ParticleCanvas } from "@/components/motionary/advanced/ParticleCanvas";
import { MagneticButton } from "@/components/motionary/atomic/MagneticButton";
import { LiquidButton } from "@/components/motionary/atomic/LiquidButton";
import { JellyButton } from "@/components/motionary/atomic/JellyButton";
import { KineticText } from "@/components/motionary/atomic/KineticText";
import { FloatingInput } from "@/components/motionary/atomic/FloatingInput";
import { ShakeInput } from "@/components/motionary/atomic/ShakeInput";
import { SwipeToDelete } from "@/components/motionary/mobile/SwipeToDelete";
import * as Buttons from "@/components/motionary/atomic/ButtonVariants";
import * as Text from "@/components/motionary/atomic/TextVariants";
import * as Cards from "@/components/motionary/atomic/CardVariants";
import * as Nav from "@/components/motionary/atomic/NavVariants";
import * as InputVars from "@/components/motionary/atomic/InputVariants";
import * as Loaders from "@/components/motionary/atomic/LoaderVariants";
import * as Images from "@/components/motionary/atomic/ImageVariants";
import * as Micro from "@/components/motionary/atomic/MicroVariants";
import * as Backgrounds from "@/components/motionary/atomic/BackgroundVariants";
import * as Data from "@/components/motionary/atomic/DataVariants";
import * as Feedback from "@/components/motionary/atomic/FeedbackVariants";
import * as Social from "@/components/motionary/atomic/SocialVariants";
import * as Ecom from "@/components/motionary/atomic/EcommerceVariants";
import * as Game from "@/components/motionary/atomic/GameVariants";
import * as Transitions from "@/components/motionary/atomic/TransitionVariants";
import * as Media from "@/components/motionary/atomic/MediaVariants";
import * as Device from "@/components/motionary/atomic/DeviceVariants";
import { useBubbleSound } from "@/hooks/useBubbleSound";
import { Footer } from "@/components/system/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Background Components for AI & Vibe Coding | Motionary",
  description: "Dynamic Background components with gradients, particles, and animations. Perfect for AI-generated interfaces and modern web design.",
  keywords: ["react backgrounds","animated backgrounds","ai coding","vibe coding","gradient backgrounds","particle effects","modern design","ui backgrounds"],
};

const BLOCK_STYLE = ["gradient", "glassmorphism"];
const MICRO_STYLE = ["minimal", "cyber"];

export default function BackgroundsPage() {
  return (
    <div className="min-h-screen pt-24 pb-20">
      <div className="max-w-[1920px] mx-auto px-6 md:px-12 space-y-8">
        
        <div className="mb-12 flex items-end gap-6 sticky top-0 bg-background/80 backdrop-blur-xl py-4 z-40 border-b border-white/5">
           <h2 className="text-4xl font-bold tracking-tight text-white"><span className="text-accent mr-4 font-mono text-2xl">05.</span>Backgrounds</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Mesh Gradient: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Mesh Gradient" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.MeshGradient /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Moving Grid: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Moving Grid" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.MovingGrid /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Dot Matrix: static motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Dot Matrix" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.DotMatrix /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Aurora: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Aurora" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.AuroraBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Neon Lines: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Neon Lines" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.NeonLines /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Starfield: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Starfield" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.StarfieldCSS /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Gradient Wave: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Gradient Wave" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.GradientWave /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Hexagon Pattern: static motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Hexagon Pattern" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.HexagonPattern /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Radial Pulse: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Radial Pulse" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.RadialPulse /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Animated Noise: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Animated Noise" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.AnimatedNoise /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Circuit Board: static motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Circuit Board" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.CircuitBoard /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Fog Flow: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Fog Flow" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.FogFlow /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Moving Stripes: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Moving Stripes" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.MovingStripes /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Rain Effect: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Rain Effect" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.RainEffect /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Fire Embers: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Fire Embers" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.FireEmbers /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Bokeh Blur: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Bokeh Blur" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.BokehBlur /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Cyber Grid: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Cyber Grid" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.CyberGrid /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Spotlight Follow: hover motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Spotlight Follow" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.SpotlightFollow /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Vignette Pulse: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Vignette Pulse" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.VignettePulse /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="TV Glitch: loop motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="TV Glitch" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.TvGlitchBg /></PlaygroundCard>
                    <PlaygroundCard styleTags={['minimal','pattern']} compType="element" promptDescription="Dot Grid Wave: static motion treatment with radial dot pattern and fade overlay. Built with Tailwind CSS." title="Dot Grid Wave" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.DotGridWave /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal','pattern']} compType="element" promptDescription="Isometric Lines: static motion treatment with angled grid lines. Built with Tailwind CSS." title="Isometric Lines Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.IsometricLinesBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern','texture']} compType="element" promptDescription="Hexagon Pulse: loop motion treatment with pulsing texture overlay. Built with Tailwind CSS." title="Hexagon Pulse Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.HexagonPulseBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['cyber','minimal']} compType="element" promptDescription="Crosshair Grid: static motion treatment with technical grid and crosshair. Built with Tailwind CSS." title="Crosshair Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.CrosshairBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['cyber','tech']} compType="element" promptDescription="Circuit Board: loop motion treatment with matrix-like shine. Built with Tailwind CSS." title="Circuit Board Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.CircuitBoardBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient','modern']} compType="element" promptDescription="Aurora Borealis: loop motion treatment with massive spinning gradient blur. Built with Tailwind CSS." title="Aurora Borealis" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.AuroraBorealis /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient','soft']} compType="element" promptDescription="Mesh Flow: loop motion treatment with multi-radial gradient rotation. Built with Tailwind CSS." title="Mesh Gradient Flow" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.MeshGradientFlow /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal','modern']} compType="element" promptDescription="Conic Spin: loop motion treatment with rotating conic light. Built with Tailwind CSS." title="Conic Spin Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.ConicSpinBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['gradient']} compType="element" promptDescription="Sunset Fade: loop motion treatment with vertical gradient pulse. Built with Tailwind CSS." title="Sunset Fade Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.SunsetFadeBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['neon','cyber']} compType="element" promptDescription="Neon Night: static motion treatment with dual vertical gradient blurs. Built with Tailwind CSS." title="Neon Night Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.NeonNightBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Mouse Spot: hover motion treatment with radial gradient tracking (requires JS for var update, CSS fallback provided). Built with Tailwind CSS." title="Mouse Follow Spot" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.MouseFollowSpot /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Ripple Click: click motion treatment with massive central ripple expand. Built with Tailwind CSS." title="Ripple Click Bg" trigger="Click" codePath="atomic/BackgroundVariants"><Backgrounds.RippleClickBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern','grid']} compType="element" promptDescription="Grid Distortion: hover motion treatment with grid scale and rotation. Built with Tailwind CSS." title="Grid Distortion C S S" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.GridDistortionCSS /></PlaygroundCard>
            <PlaygroundCard styleTags={['space','minimal']} compType="element" promptDescription="Parallax Stars: hover motion treatment with multi-layer background movement. Built with Tailwind CSS." title="Parallax Stars Bg" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.ParallaxStarsBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Blur Focus: hover motion treatment with background image unblur. Built with Tailwind CSS." title="Blur Focus Bg" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.BlurFocusBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern','organic']} compType="element" promptDescription="Abstract Shapes: loop motion treatment with moving blurred blobs. Built with Tailwind CSS." title="Abstract Shapes Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.AbstractShapesBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['cyber','retro']} compType="element" promptDescription="Matrix Rain: loop motion treatment with falling text columns. Built with Tailwind CSS." title="Matrix Rain C S S" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.MatrixRainCSS /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal','pattern']} compType="element" promptDescription="Stripes: static motion treatment with diagonal repeating stripes. Built with Tailwind CSS." title="Stripes Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.StripesBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['retro','pattern']} compType="element" promptDescription="Zig Zag: static motion treatment with geometric zig zag pattern. Built with Tailwind CSS." title="Zig Zag Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.ZigZagBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['retro','pattern']} compType="element" promptDescription="Polka Dot: hover motion treatment with background color shift on pattern. Built with Tailwind CSS." title="Polka Dot Bg" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.PolkaDotBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['soft','gradient']} compType="element" promptDescription="Warm Glow: loop motion treatment with pulsing central warm light. Built with Tailwind CSS." title="Warm Glow Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.WarmGlowBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Cold Steel: hover motion treatment with metallic sheen overlay. Built with Tailwind CSS." title="Cold Steel Bg" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.ColdSteelBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Vignette: static motion treatment with dark radial corners. Built with Tailwind CSS." title="Vignette Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.VignetteBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['texture']} compType="element" promptDescription="Grainy Noise: static motion treatment with SVG filter noise. Built with Tailwind CSS." title="Grainy Noise Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.GrainyNoiseBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern']} compType="element" promptDescription="Gradient Border: static motion treatment with rainbow border container. Built with Tailwind CSS." title="Gradient Border Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.GradientBorderBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['organic']} compType="element" promptDescription="Circle Scatter: loop motion treatment with random pulsing dots. Built with Tailwind CSS." title="Circle Scatter Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.CircleScatterBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['cyber']} compType="element" promptDescription="Line Flow: loop motion treatment with horizontal scanning light. Built with Tailwind CSS." title="Line Flow Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.LineFlowBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['retro','pattern']} compType="element" promptDescription="Checkerboard: static motion treatment with classic checker pattern. Built with Tailwind CSS." title="Checkerboard Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.CheckerboardBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern','interaction']} compType="element" promptDescription="Split Color: hover motion treatment with dual pane flex expansion. Built with Tailwind CSS." title="Split Color Bg" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.SplitColorBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['transition']} compType="element" promptDescription="Diagonal Slide: hover motion treatment with full screen wipe overlay. Built with Tailwind CSS." title="Diagonal Slide Bg" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.DiagonalSlideBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['nature']} compType="element" promptDescription="Aurora Borealis: loop motion treatment with northern lights. Built with Tailwind CSS." title="Aurora Borealis" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.AuroraBorealis /></PlaygroundCard>
            <PlaygroundCard styleTags={['nature']} compType="element" promptDescription="Sunset Shift: loop motion treatment with evening sky. Built with Tailwind CSS." title="Sunset Shift" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.SunsetShift /></PlaygroundCard>
            <PlaygroundCard styleTags={['nature']} compType="element" promptDescription="Deep Sea: loop motion treatment with underwater depth. Built with Tailwind CSS." title="Deep Sea Gradient" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.DeepSeaGradient /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern']} compType="element" promptDescription="Holographic Foil: loop motion treatment with iridescent color. Built with Tailwind CSS." title="Holographic Foil" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.HolographicFoil /></PlaygroundCard>
            <PlaygroundCard styleTags={['tech']} compType="element" promptDescription="Dot Matrix: loop motion treatment with scrolling points. Built with Tailwind CSS." title="Dot Matrix Scroll" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.DotMatrixScroll /></PlaygroundCard>
            <PlaygroundCard styleTags={['retro']} compType="element" promptDescription="Perspective Grid: loop motion treatment with synthwave floor. Built with Tailwind CSS." title="Grid Perspective Plane" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.GridPerspectivePlane /></PlaygroundCard>
            <PlaygroundCard styleTags={['pattern']} compType="element" promptDescription="Hexagon Hive: static motion treatment with geometric repeat. Built with Tailwind CSS." title="Hexagon Hive" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.HexagonHive /></PlaygroundCard>
            <PlaygroundCard styleTags={['pattern']} compType="element" promptDescription="Zigzag Scroll: loop motion treatment with diagonal movement. Built with Tailwind CSS." title="Zigzag Scroll" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.ZigzagScroll /></PlaygroundCard>
            <PlaygroundCard styleTags={['nature']} compType="element" promptDescription="Fireflies: loop motion treatment with random light bugs. Built with Tailwind CSS." title="Fireflies Swarm" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.FirefliesSwarm /></PlaygroundCard>
            <PlaygroundCard styleTags={['nature']} compType="element" promptDescription="Snowfall: loop motion treatment with dropping flakes. Built with Tailwind CSS." title="Snowfall Simple" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.SnowfallSimple /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Dust Motes: loop motion treatment with ambient particles. Built with Tailwind CSS." title="Dust Motes" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.DustMotes /></PlaygroundCard>
            <PlaygroundCard styleTags={['sci-fi']} compType="element" promptDescription="Star Warp: loop motion treatment with hyperspace jump. Built with Tailwind CSS." title="Starfield Warp" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.StarfieldWarp /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Mouse Glow: hover motion treatment with cursor light. Built with Tailwind CSS." title="Mouse Trail Glow" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.MouseTrailGlow /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Click Ripple Bg: click motion treatment with flash response. Built with Tailwind CSS." title="Click Ripple Bg" trigger="Click" codePath="atomic/BackgroundVariants"><Backgrounds.ClickRippleBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern']} compType="element" promptDescription="Parallax Bg: hover motion treatment with slow zoom. Built with Tailwind CSS." title="Parallax Layer Bg" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.ParallaxLayerBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['creative']} compType="element" promptDescription="Spotlight Reveal: hover motion treatment with hidden content. Built with Tailwind CSS." title="Spotlight Reveal Bg" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.SpotlightRevealBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['abstract']} compType="element" promptDescription="Lava Lamp: loop motion treatment with gooey blobs. Built with Tailwind CSS." title="Lava Lamp Blobs" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.LavaLampBlobs /></PlaygroundCard>
            <PlaygroundCard styleTags={['retro']} compType="element" promptDescription="Noise Static: loop motion treatment with tv grain. Built with Tailwind CSS." title="Noise Static Tv" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.NoiseStaticTv /></PlaygroundCard>
            <PlaygroundCard styleTags={['abstract']} compType="element" promptDescription="Liquid Blobs: loop motion treatment with pastel mix. Built with Tailwind CSS." title="Liquid Blobs Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.LiquidBlobsBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['glass']} compType="element" promptDescription="Glass Prism: loop motion treatment with frosted overlay. Built with Tailwind CSS." title="Glass Prism Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.GlassPrismBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['pattern']} compType="element" promptDescription="Diagonal Stripes: static motion treatment with caution pattern. Built with Tailwind CSS." title="Diagonal Stripes" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.DiagonalStripes /></PlaygroundCard>
            <PlaygroundCard styleTags={['tech']} compType="element" promptDescription="Circuit Board: static motion treatment with tech lines. Built with Tailwind CSS." title="Circuit Board Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.CircuitBoardBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['abstract']} compType="element" promptDescription="Floating Squares: loop motion treatment with geometric drift. Built with Tailwind CSS." title="Floating Squares" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.FloatingSquares /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Radial Pulse: loop motion treatment with center glow. Built with Tailwind CSS." title="Radial Pulse Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.RadialPulseBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['tech']} compType="element" promptDescription="Moving Grid: loop motion treatment with horizontal slide. Built with Tailwind CSS." title="Grid Move Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.GridMoveBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['retro']} compType="element" promptDescription="Cyber Grid: static motion treatment with retro landscape. Built with Tailwind CSS." title="Cyber Grid Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.CyberGridBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Vignette Pulse: loop motion treatment with dark edges. Built with Tailwind CSS." title="Vignette Pulse" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.VignettePulse /></PlaygroundCard>
            <PlaygroundCard styleTags={['retro']} compType="element" promptDescription="Scanline: loop motion treatment with screen refresh. Built with Tailwind CSS." title="Scanline Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.ScanlineBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['abstract']} compType="element" promptDescription="Bokeh: static motion treatment with soft lights. Built with Tailwind CSS." title="Bokeh Bg" trigger="Static" codePath="atomic/BackgroundVariants"><Backgrounds.BokehBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Pattern Morph: hover motion treatment with scale shift. Built with Tailwind CSS." title="Pattern Morph Bg" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.PatternMorphBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern']} compType="element" promptDescription="Interact Gradient: hover motion treatment with color transition. Built with Tailwind CSS." title="Interactive Gradient" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.InteractiveGradient /></PlaygroundCard>
            <PlaygroundCard styleTags={['nature']} compType="element" promptDescription="Rain Window: loop motion treatment with falling drops. Built with Tailwind CSS." title="Rain Window" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.RainWindow /></PlaygroundCard>
            <PlaygroundCard styleTags={['retro']} compType="element" promptDescription="Matrix Code: loop motion treatment with digital rain. Built with Tailwind CSS." title="Matrix Code Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.MatrixCodeBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['fun']} compType="element" promptDescription="Floating Bubbles: loop motion treatment with rising spheres. Built with Tailwind CSS." title="Floating Bubbles Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.FloatingBubblesBg /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Spotlight Follow: hover motion treatment with simple light. Built with Tailwind CSS." title="Spotlight Follow" trigger="Hover" codePath="atomic/BackgroundVariants"><Backgrounds.SpotlightFollow /></PlaygroundCard>
            <PlaygroundCard styleTags={['cyber']} compType="element" promptDescription="Glitch Bg: loop motion treatment with chromatic shift. Built with Tailwind CSS." title="Glitch Background" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.GlitchBackground /></PlaygroundCard>
            <PlaygroundCard styleTags={['nature']} compType="element" promptDescription="Waves Bg: loop motion treatment with ocean sine. Built with Tailwind CSS." title="Waves Bg" trigger="Loop" codePath="atomic/BackgroundVariants"><Backgrounds.WavesBg /></PlaygroundCard>
</div>
      
      </div>
    </div>
  );
}
