import React from 'react';
import { PlaygroundCard } from "@/components/system/PlaygroundCard";
import { useFilterStore } from "@/store/useFilterStore";
import { HeroGradient } from "@/components/motionary/blocks/HeroGradient";
import { BentoGrid } from "@/components/motionary/blocks/BentoGrid";
import { PricingSection } from "@/components/motionary/blocks/PricingSection";
import { LandingPage } from "@/components/motionary/blocks/LandingPage";
import { ParticleCanvas } from "@/components/motionary/advanced/ParticleCanvas";
import { MagneticButton } from "@/components/motionary/atomic/MagneticButton";
import { LiquidButton } from "@/components/motionary/atomic/LiquidButton";
import { JellyButton } from "@/components/motionary/atomic/JellyButton";
import { KineticText } from "@/components/motionary/atomic/KineticText";
import { FloatingInput } from "@/components/motionary/atomic/FloatingInput";
import { ShakeInput } from "@/components/motionary/atomic/ShakeInput";
import { SwipeToDelete } from "@/components/motionary/mobile/SwipeToDelete";
import * as Buttons from "@/components/motionary/atomic/ButtonVariants";
import * as Text from "@/components/motionary/atomic/TextVariants";
import * as Cards from "@/components/motionary/atomic/CardVariants";
import * as Nav from "@/components/motionary/atomic/NavVariants";
import * as InputVars from "@/components/motionary/atomic/InputVariants";
import * as Loaders from "@/components/motionary/atomic/LoaderVariants";
import * as Images from "@/components/motionary/atomic/ImageVariants";
import * as Micro from "@/components/motionary/atomic/MicroVariants";
import * as Backgrounds from "@/components/motionary/atomic/BackgroundVariants";
import * as Data from "@/components/motionary/atomic/DataVariants";
import * as Feedback from "@/components/motionary/atomic/FeedbackVariants";
import * as Social from "@/components/motionary/atomic/SocialVariants";
import * as Ecom from "@/components/motionary/atomic/EcommerceVariants";
import * as Game from "@/components/motionary/atomic/GameVariants";
import * as Transitions from "@/components/motionary/atomic/TransitionVariants";
import * as Media from "@/components/motionary/atomic/MediaVariants";
import * as Device from "@/components/motionary/atomic/DeviceVariants";
import { useBubbleSound } from "@/hooks/useBubbleSound";
import { Footer } from "@/components/system/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Input Components for AI & Vibe Coding | Motionary",
  description: "Form Input components with animations and modern design. Text fields, selects, checkboxes optimized for AI code generation and Cursor compatibility.",
  keywords: ["react inputs","form components","ai coding","vibe coding","animated inputs","modern forms","ui inputs","cursor compatible"],
};

const BLOCK_STYLE = ["gradient", "glassmorphism"];
const MICRO_STYLE = ["minimal", "cyber"];

export default function InputsPage() {
  return (
    <div className="min-h-screen pt-24 pb-20">
      <div className="max-w-[1920px] mx-auto px-6 md:px-12 space-y-8">
        
         <div className="mb-12 flex items-end gap-6 sticky top-0 bg-background/80 backdrop-blur-xl py-4 z-40 border-b border-white/5">
           <h2 className="text-4xl font-bold tracking-tight text-white"><span className="text-white/50 mr-4 font-mono text-2xl">09.</span>Inputs</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Floating Label: focus motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Floating Label" trigger="Focus" codePath="atomic/InputVariants"><div className="w-full max-w-[200px]"><InputVars.FloatingLabelInput /></div></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Shake Error: validation motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Shake Error" trigger="Validation" codePath="atomic/InputVariants"><InputVars.ShakeErrorInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Border Spread: focus motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Border Spread" trigger="Focus" codePath="atomic/InputVariants"><InputVars.BorderSpreadInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Password Reveal: click motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Password Reveal" trigger="Click" codePath="atomic/InputVariants"><InputVars.PasswordReveal /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Search Expand: click motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Search Expand" trigger="Click" codePath="atomic/InputVariants"><InputVars.SearchExpandInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="OTP Input: input motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="OTP Input" trigger="Input" codePath="atomic/InputVariants"><InputVars.OTPInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Tag Input: enter motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Tag Input" trigger="Enter" codePath="atomic/InputVariants"><InputVars.TagInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="File Dropzone: drag motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="File Dropzone" trigger="Drag" codePath="atomic/InputVariants"><InputVars.FileDropzone /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Voice Wave: click motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Voice Wave" trigger="Click" codePath="atomic/InputVariants"><InputVars.VoiceInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Credit Card: focus motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Credit Card" trigger="Focus" codePath="atomic/InputVariants"><InputVars.CreditCardInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Char Count: input motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Char Count" trigger="Input" codePath="atomic/InputVariants"><InputVars.CharCountInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Material Fill: focus motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Material Fill" trigger="Focus" codePath="atomic/InputVariants"><InputVars.MaterialFilledInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Inline Submit: input motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Inline Submit" trigger="Input" codePath="atomic/InputVariants"><InputVars.InlineSubmitInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Auto Resize: input motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Auto Resize" trigger="Input" codePath="atomic/InputVariants"><InputVars.AutoResizeTextarea /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Color Picker: click motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Color Picker" trigger="Click" codePath="atomic/InputVariants"><InputVars.ColorInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Stepper: click motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Stepper" trigger="Click" codePath="atomic/InputVariants"><InputVars.StepperInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Copy Clipboard: click motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Copy Clipboard" trigger="Click" codePath="atomic/InputVariants"><InputVars.CopyInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Range Slider: drag motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Range Slider" trigger="Drag" codePath="atomic/InputVariants"><InputVars.SliderInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Chat Input: focus motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Chat Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.ChatInput /></PlaygroundCard>
           <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Mentions: static motion treatment built with React + Tailwind + framer-motion. Include its signature visual/interaction cues true to the name." title="Mentions" trigger="Static" codePath="atomic/InputVariants"><InputVars.MentionInput /></PlaygroundCard>
                    <PlaygroundCard styleTags={['minimal','form']} compType="element" promptDescription="Underline Input: focus motion treatment with floating label and bottom border. Built with Tailwind CSS." title="Underline Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.UnderlineInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Search Expand Icon: click/focus motion treatment with pill expansion. Built with Tailwind CSS." title="Search Expand Icon" trigger="Focus" codePath="atomic/InputVariants"><InputVars.SearchExpandIcon /></PlaygroundCard>
            <PlaygroundCard styleTags={['feedback']} compType="element" promptDescription="Validation Shake: error motion treatment with input shake animation. Built with Tailwind CSS." title="Validation Shake" trigger="Validation" codePath="atomic/InputVariants"><InputVars.ValidationShake /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern']} compType="element" promptDescription="Gradient Border Input: focus motion treatment with rainbow border container. Built with Tailwind CSS." title="Gradient Border Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.GradientBorderInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['material','form']} compType="element" promptDescription="Material Outline: focus motion treatment with cutout label animation. Built with Tailwind CSS." title="Material Outline" trigger="Focus" codePath="atomic/InputVariants"><InputVars.MaterialOutline /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Day Night Switch: click motion treatment with icon toggle. Built with Tailwind CSS." title="Day Night Switch" trigger="Click" codePath="atomic/InputVariants"><InputVars.DayNightSwitch /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Elastic Toggle: click motion treatment with springy bezier transition. Built with Tailwind CSS." title="Elastic Toggle" trigger="Click" codePath="atomic/InputVariants"><InputVars.ElasticToggle /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Neumorphic Toggle: click motion treatment with inner shadow depth. Built with Tailwind CSS." title="Neumorphic Toggle" trigger="Click" codePath="atomic/InputVariants"><InputVars.NeumorphicToggle /></PlaygroundCard>
            <PlaygroundCard styleTags={['3d']} compType="element" promptDescription="Flip Switch: click motion treatment with 3D rotate state change. Built with Tailwind CSS." title="Flip Switch" trigger="Click" codePath="atomic/InputVariants"><InputVars.FlipSwitch /></PlaygroundCard>
            <PlaygroundCard styleTags={['organic']} compType="element" promptDescription="Liquid Switch: click motion treatment with ink spread fill. Built with Tailwind CSS." title="Liquid Switch" trigger="Click" codePath="atomic/InputVariants"><InputVars.LiquidSwitch /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Bounce Check: click motion treatment with scale feedback. Built with Tailwind CSS." title="Bounce Check" trigger="Click" codePath="atomic/InputVariants"><InputVars.BounceCheck /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Ripple Radio: click motion treatment with ping ring effect. Built with Tailwind CSS." title="Ripple Radio" trigger="Click" codePath="atomic/InputVariants"><InputVars.RippleRadio /></PlaygroundCard>
            <PlaygroundCard styleTags={['neon']} compType="element" promptDescription="Neon Checkbox: click motion treatment with glow activation. Built with Tailwind CSS." title="Neon Checkbox" trigger="Click" codePath="atomic/InputVariants"><InputVars.NeonCheckbox /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Strike Through: click motion treatment with text decoration animation. Built with Tailwind CSS." title="Strike Through Check" trigger="Click" codePath="atomic/InputVariants"><InputVars.StrikeThroughCheck /></PlaygroundCard>
            <PlaygroundCard styleTags={['social']} compType="element" promptDescription="Heart Checkbox: click motion treatment with SVG fill transition. Built with Tailwind CSS." title="Heart Checkbox" trigger="Click" codePath="atomic/InputVariants"><InputVars.HeartCheckbox /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Tooltip Slider: drag motion treatment with value bubble reveal. Built with Tailwind CSS." title="Tooltip Slider" trigger="Drag" codePath="atomic/InputVariants"><InputVars.TooltipSlider /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern']} compType="element" promptDescription="Thick Slider: drag motion treatment with fill track via shadow hack. Built with Tailwind CSS." title="Thick Range Slider" trigger="Drag" codePath="atomic/InputVariants"><InputVars.ThickRangeSlider /></PlaygroundCard>
            <PlaygroundCard styleTags={['media']} compType="element" promptDescription="Vertical Slider: drag motion treatment with volume bar simulation. Built with Tailwind CSS." title="Vertical Slider" trigger="Drag" codePath="atomic/InputVariants"><InputVars.VerticalSlider /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Step Slider: click motion treatment with discrete snap points. Built with Tailwind CSS." title="Step Slider" trigger="Click" codePath="atomic/InputVariants"><InputVars.StepSlider /></PlaygroundCard>
            <PlaygroundCard styleTags={['media']} compType="element" promptDescription="Icon Slider: drag motion treatment with volume iconography. Built with Tailwind CSS." title="Icon Slider" trigger="Drag" codePath="atomic/InputVariants"><InputVars.IconSlider /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Pin Code: focus motion treatment with multi-box focus ring. Built with Tailwind CSS." title="Pin Code Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.PinCodeInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Drag Drop: hover motion treatment with dashed border activation. Built with Tailwind CSS." title="Drag Drop Zone" trigger="Hover" codePath="atomic/InputVariants"><InputVars.DragDropZone /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Signature Pad: hover motion treatment with path drawing simulation. Built with Tailwind CSS." title="Signature Pad" trigger="Hover" codePath="atomic/InputVariants"><InputVars.SignaturePad /></PlaygroundCard>
            <PlaygroundCard styleTags={['form','minimal']} compType="element" promptDescription="Chip Select: click motion treatment with pill selection state. Built with Tailwind CSS." title="Chip Select" trigger="Click" codePath="atomic/InputVariants"><InputVars.ChipSelect /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Currency Input: focus motion treatment with prefix color activation. Built with Tailwind CSS." title="Currency Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.CurrencyInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Multi Range: drag motion treatment with dual thumb track. Built with Tailwind CSS." title="Multi Range Slider" trigger="Drag" codePath="atomic/InputVariants"><InputVars.MultiRangeSlider /></PlaygroundCard>
            <PlaygroundCard styleTags={['media','interaction']} compType="element" promptDescription="Knob Control: drag motion treatment with radial rotation value. Built with Tailwind CSS." title="Knob Control" trigger="Drag" codePath="atomic/InputVariants"><InputVars.KnobControl /></PlaygroundCard>
            <PlaygroundCard styleTags={['feedback','form']} compType="element" promptDescription="Rating Star: hover motion treatment with sequential fill. Built with Tailwind CSS." title="Rating Star Input" trigger="Hover" codePath="atomic/InputVariants"><InputVars.RatingStarInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Color Palette: click motion treatment with swatch selection scale. Built with Tailwind CSS." title="Color Palette Input" trigger="Click" codePath="atomic/InputVariants"><InputVars.ColorPaletteInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['form','complex']} compType="element" promptDescription="Date Picker: hover motion treatment with dropdown calendar reveal. Built with Tailwind CSS." title="Date Picker Sim" trigger="Hover" codePath="atomic/InputVariants"><InputVars.DatePickerSim /></PlaygroundCard>
            <PlaygroundCard styleTags={['material']} compType="element" promptDescription="Material Line: focus motion treatment with floating label. Built with Tailwind CSS." title="Material Line Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.MaterialLineInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['modern']} compType="element" promptDescription="Outline Cut: focus motion treatment with border notch. Built with Tailwind CSS." title="Outline Cut Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.OutlineCutInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Background Fill: focus motion treatment with surface fill. Built with Tailwind CSS." title="Background Fill Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.BackgroundFillInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Icon Morph: focus motion treatment with icon color shift. Built with Tailwind CSS." title="Icon Morph Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.IconMorphInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Card Radio: click motion treatment with border highlight. Built with Tailwind CSS." title="Card Radio Select" trigger="Click" codePath="atomic/InputVariants"><InputVars.CardRadioSelect /></PlaygroundCard>
            <PlaygroundCard styleTags={['media']} compType="element" promptDescription="Image Checkbox: click motion treatment with selection overlay. Built with Tailwind CSS." title="Image Checkbox Grid" trigger="Click" codePath="atomic/InputVariants"><InputVars.ImageCheckboxGrid /></PlaygroundCard>
            <PlaygroundCard styleTags={['minimal']} compType="element" promptDescription="Tag Cloud: click motion treatment with pill activation. Built with Tailwind CSS." title="Tag Cloud Select" trigger="Click" codePath="atomic/InputVariants"><InputVars.TagCloudSelect /></PlaygroundCard>
            <PlaygroundCard styleTags={['ios']} compType="element" promptDescription="Segmented Control: click motion treatment (simulated) with sliding background. Built with Tailwind CSS." title="Segmented Control" trigger="Click" codePath="atomic/InputVariants"><InputVars.SegmentedControl /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Dropzone Bounce: drag motion treatment with upload prompt. Built with Tailwind CSS." title="Dropzone Bounce" trigger="Drag" codePath="atomic/InputVariants"><InputVars.DropzoneBounce /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="File Stack: hover motion treatment with card spread. Built with Tailwind CSS." title="File Preview Stack" trigger="Hover" codePath="atomic/InputVariants"><InputVars.FilePreviewStack /></PlaygroundCard>
            <PlaygroundCard styleTags={['status']} compType="element" promptDescription="Multi Upload: load motion treatment with progress list. Built with Tailwind CSS." title="Multi Upload List" trigger="Load" codePath="atomic/InputVariants"><InputVars.MultiUploadList /></PlaygroundCard>
            <PlaygroundCard styleTags={['audio']} compType="element" promptDescription="Vertical Range: drag motion treatment with volume level. Built with Tailwind CSS." title="Vertical Range Slider" trigger="Drag" codePath="atomic/InputVariants"><InputVars.VerticalRangeSlider /></PlaygroundCard>
            <PlaygroundCard styleTags={['skeuomorphic']} compType="element" promptDescription="Knob Control: drag motion treatment with rotational dial. Built with Tailwind CSS." title="Knob Rotate Control" trigger="Drag" codePath="atomic/InputVariants"><InputVars.KnobRotateControl /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Date Picker: hover motion treatment with dropdown indicator. Built with Tailwind CSS." title="Date Picker Flip" trigger="Hover" codePath="atomic/InputVariants"><InputVars.DatePickerFlip /></PlaygroundCard>
            <PlaygroundCard styleTags={['creative']} compType="element" promptDescription="Color Wheel: hover motion treatment with spectrum selection. Built with Tailwind CSS." title="Color Wheel Pick" trigger="Hover" codePath="atomic/InputVariants"><InputVars.ColorWheelPick /></PlaygroundCard>
            <PlaygroundCard styleTags={['security']} compType="element" promptDescription="Pattern Lock: hover motion treatment with grid dots. Built with Tailwind CSS." title="Pattern Lock" trigger="Hover" codePath="atomic/InputVariants"><InputVars.PatternLock /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Stepper Btn: click motion treatment with increment controls. Built with Tailwind CSS." title="Stepper Buttons" trigger="Click" codePath="atomic/InputVariants"><InputVars.StepperButtons /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Dual Range: drag motion treatment with range selection. Built with Tailwind CSS." title="Dual Range Slider" trigger="Drag" codePath="atomic/InputVariants"><InputVars.DualRangeSlider /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Voice Record: click motion treatment with mic activation. Built with Tailwind CSS." title="Voice Record Btn" trigger="Click" codePath="atomic/InputVariants"><InputVars.VoiceRecordBtn /></PlaygroundCard>
            <PlaygroundCard styleTags={['3d']} compType="element" promptDescription="Card Flip: hover motion treatment with CVV reveal. Built with Tailwind CSS." title="Credit Card Flip" trigger="Hover" codePath="atomic/InputVariants"><InputVars.CreditCardFlip /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Address Fill: focus motion treatment with suggestions dropdown. Built with Tailwind CSS." title="Address Autofill" trigger="Focus" codePath="atomic/InputVariants"><InputVars.AddressAutofill /></PlaygroundCard>
            <PlaygroundCard styleTags={['security']} compType="element" promptDescription="Pass Strength: hover motion treatment with meter feedback. Built with Tailwind CSS." title="Password Strength" trigger="Hover" codePath="atomic/InputVariants"><InputVars.PasswordStrength /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Currency Flag: focus motion treatment with prefix selector. Built with Tailwind CSS." title="Currency Flag" trigger="Focus" codePath="atomic/InputVariants"><InputVars.CurrencyFlag /></PlaygroundCard>
            <PlaygroundCard styleTags={['editor']} compType="element" promptDescription="Markdown Edit: focus motion treatment with syntax highlighting (simulated). Built with Tailwind CSS." title="Markdown Editor" trigger="Focus" codePath="atomic/InputVariants"><InputVars.MarkdownEditor /></PlaygroundCard>
            <PlaygroundCard styleTags={['ui']} compType="element" promptDescription="Drag List: drag motion treatment with placeholder ghost. Built with Tailwind CSS." title="Drag Drop List" trigger="Drag" codePath="atomic/InputVariants"><InputVars.DragDropList /></PlaygroundCard>
            <PlaygroundCard styleTags={['editor']} compType="element" promptDescription="Rich Toolbar: hover motion treatment with button states. Built with Tailwind CSS." title="Rich Text Toolbar" trigger="Hover" codePath="atomic/InputVariants"><InputVars.RichTextToolbar /></PlaygroundCard>
            <PlaygroundCard styleTags={['interaction']} compType="element" promptDescription="Emoji Picker: hover motion treatment with popover grid. Built with Tailwind CSS." title="Emoji Picker Trigger" trigger="Hover" codePath="atomic/InputVariants"><InputVars.EmojiPickerTrigger /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Input Clear: hover motion treatment with reset icon. Built with Tailwind CSS." title="Input Clear Button" trigger="Hover" codePath="atomic/InputVariants"><InputVars.InputClearButton /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Chip Input: focus motion treatment with tag entry. Built with Tailwind CSS." title="Chip Input" trigger="Focus" codePath="atomic/InputVariants"><InputVars.ChipInput /></PlaygroundCard>
            <PlaygroundCard styleTags={['form']} compType="element" promptDescription="Signature: hover motion treatment with ink flow. Built with Tailwind CSS." title="Signature Sign" trigger="Hover" codePath="atomic/InputVariants"><InputVars.SignatureSign /></PlaygroundCard>
</div>
      
      </div>
    </div>
  );
}
